---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: dev
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCGMIc8IHbbrsupEMeO39VtLxCNE1e9vYyeCQ40Cj0ZTMWDLch6yILBQt1WVuoJaGi/yhMBHGVlaPN/yw6OzqTb+MCcHleBcOyqKYJiBx1DwYEzVmSz3Nfd0juMC+gOwDjgSpQUZGmVXVyK/sYrbt6pkGcVS4AazUEZioLyD/5hOiih8iEh3mClhGpENidZ9zfiIXWHp1VFYmOq/Jnel1jV9qeaTVWf2o0XrOMPM5jZijYwzD0+exYNZ3Ic5MC/sE5DPx/00WIFY2sv4h/hdWc86ExtDFz5duhE8d/dtsufM89GMkvSlK8++J1E3YAOGlBnZG7BlJf7fNBxrNMBucYOmCIYsuwNmsxm/5VX3OVm06fiFMqXawSFNCOPYONL5PWUH83ww7ugW3/CorQJybd7oPCyaP9Xtg8WIFZyBit6sWX/9NYHVkEAwDsHjSz/jEbNv9zvVJ2iQvfvdP2A3/n0w1ysv4NACS4vPfhCIgNaesvUJBHjv3tUX7dQ4NRXz/IEv6CqijYNaL+zu3XyHdj3dcVCGx1HITPgucDOcMn6+5QCfHHJzikvoeFDIruCsNA+sj5vLrTG8V8568MPxltZTRJIKlCN/GNQPT+2xwQhnmUOPcRy6OPWTXGZxoUtmKVZyMOrwwmK/1lEwsrGgyssAeigpR9uIA2EF6h+wv/pMX43H76g4V9RYKpzOo9Qkp9aQUcZkZ7TsXKAbyojkFaegkSzkA==
    ACCESS_SECRET_KEY: AgC7yWgS2xFB75sj2xkDbGrdI2LY3OYiSRQxHDuU4qpvTIICEAHUDj4GcLqJYnRH58tYOsc1JJRcaHyMf3Z7ESVF0+3iwOQer26vRL9jGcyBS0qhse44H4O/b+N1tO3dPjkHc0A0XcELkx/9ZoabiiQDamAYs4KoPpj2Z5EXioni0gaHZ5cmnwkFEhPhCyKxjIUuAqG6rVoylTZRQclRuVp0rVpt3xN1GIMkVEkv118C5RoYhfAK1Slsj/PWeDKz+X1e1H72GVYH8u7Cbijr5lX6dmumiHfA8KX8OzmWAQgnKS5BNIS934bdQV97fZYb84B/zFoRBNKQLsTXrNmvLof6+AsWKTOKOdiuZ1aLid9xpo0MScmqvoibbCsTzR2fENWQ+cV0izqbZClO+DJWtULwSiMChsNK3SsG4ZmAsD22aRQPmIUc8NBWyTei1GSe92+FC/qAVayJ2u3JJYJ5tk2Ckd+SakafvrA1tsmv5xM0Uy5aiUZ2CxWQ8VOtP9kKAqqBcWvm1K2Re62hOzV40XXCZd4yh67sHXDXLgPISE6zw2PSVS0orqEfushqM+Eys88deweojPRUlgE5ZDOacMZhoZCrr4CYkvkRRjXufWPvAkJ008wdDUmAjx76Yy3OdI6ZRXSr66ksLoCpL2/yLv3UdeUEr2uaJekUOoKhWkHT95sBX9rorD296dTIurvLri653K9+cksbWL62Kgfw4M0mvnERp2bMyhBfpWhq2dgyYF4Dv5ieuQyu
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: dev
