---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate
  namespace: core
spec:
  secretName: certificate-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  commonName: "*.<path:core:paths#domain>"
  dnsNames:
  - "<path:core:paths#domain>"
  - "*.<path:core:paths#domain>"