apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: []
#   - deployment.yaml
#   - ingress.yaml
#   - service.yaml
#   - volume-claim.yaml

# images:
# - name: uptime-kuma
#   newName: louislam/uptime-kuma
#   newTag: "1.23.16"