apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment/deployment.yaml
  - deployment/ingress.yaml
  - deployment/service.yaml
  - deployment/volume-claim.yaml

  - mariadb/mariadb.yaml
  - mariadb/backup.yaml

  - secrets.yaml

images:
- name: uptime-kuma
  newName: louislam/uptime-kuma
  newTag: "2.0.0-beta-slim.1"