---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: uptime-secret
  namespace: metrics
spec:
  encryptedData:
    UPTIME_KUMA_DB_PASSWORD: AgB7QJixtROVlgWIJG12L8LS8zMDWqnNralMWSw881rLWbjBHYOKvZn3K+qR3ABQOBgn5MFiwVQ9ObNR7dxj+JHrfcg/RdGBIdQhxvB/qtY94XBqkptqqcHqML67GZMEYjrP8IqLcwYfXliaOMNOpLvzOTLmTykTnIKs8ZunxhzNmpmq0cgLZg37CZVXk9WXzwW9Lpi1eBT0lVbfWbGyrZjFynEXI2fFtA7Lb0e1ibrYCHg7qMU0eLzw76x83PLuKsKuqND9qYODv+HlcfwJEi6ybzd24f1B2KJQp2JKTOW5CdcgSfaeKyK3TsfcTB4349NE7usYhSv0zndcFz6eMwzcLbsJGxQ2LKKT21krzK8mBuSZbLLc6xKPM9k1WZroGlMVvvoFtuKGLFwgFVz+0doYAp6wog3m3Y+oNMDaAN83eyVWdheyxUJElJWVknzA9CYlpvxI3FDIGxu8+f3rzdZ9qnVFGsUs8/chPxgt0RjrtBDAAsyXN/GvgjhRMY0/1FPZ/7F/GOtYS1SqUONXMPyQ+J8XHrsPme5k15VJpDI+dGDiewaUUq+AE2TuyG9sWHR/gjmLmsPxJmZb6qAXtLutjPFrzJqzaRQjt7f/611ha4d0OD17fIaomQG1XUj8UYWTm5A9P/cne/L2DTnLme7V6Rtx3aGf54ZwcKAiPPGkfF9x4gUB3TPg9Y+xvVj4AJGOkbGrDqX7OKFelNm2W9Niw7/ZRGqOnWg=
  template:
    metadata:
      creationTimestamp: null
      name: uptime-secret
      namespace: metrics
