grafana:

  initChownData:
    enabled: false

  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    fsGroup: 65534

  persistence:
    type: pvc
    enabled: true
    storageClassName: nfs-csi
    accessModes:
    - ReadWriteMany
    size: 10Gi

  admin:
    existingSecret: grafana-secret
    userKey: admin-user
    passwordKey: admin-password

  service:
    port: 3000
    targetPort: 3000

  grafana.ini:
    database:
      type: postgres
      host: grafana-postgres-rw:5432
      name: grafana
      user: ${DB_USERNAME}
      password: ${DB_PASSWORD}

  envValueFrom:
    DB_USERNAME:
      secretKeyRef:
        key: username
        name: grafana-secret
    DB_PASSWORD:
      secretKeyRef:
        key: password
        name: grafana-secret

  # envFromSecret: grafana-secret

  logLevel: INFO