apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment/deployment.yaml
  - deployment/ingress.yaml
  - deployment/service.yaml
  - deployment/volume-claim.yaml

  - postgres/postgres.yaml
  - postgres/backup.yaml

  - secrets.yaml