apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-gallery-backup
spec:
  schedule: "0 0 0 * * 0"
  backupOwnerReference: self
  cluster:
    name: immich-gallery-postgres