apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-gallery-postgres
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16.3-v0.2.1
  postgresql:
    shared_preload_libraries:
      - "vectors.so"
    enableAlterSystem: true
  
  bootstrap:
    initdb:
      database: immich-gallery
      owner: immich-gallery
      secret:
        name: immich-gallery-secret
      postInitApplicationSQL:
        - ALTER SYSTEM SET search_path TO "$user", public, vectors;
        - SET search_path TO "$user", public, vectors;
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube";
        - CREATE EXTENSION IF NOT EXISTS "earthdistance";
        - ALTER SCHEMA vectors OWNER TO "immich-gallery";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA vectors TO "immich-gallery";
        - GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "immich-gallery";

  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-immich-gallery/
      endpointURL: https://thorium.<path:core:paths#domain>
      s3Credentials:
        accessKeyId:
          name: minio-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: minio-creds
          key: ACCESS_SECRET_KEY

  storage:
    storageClass: local-default
    size: 1Gi