---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-gallery
spec:
  revisionHistoryLimit: 3
  replicas: 1
  selector:
    matchLabels:
      name: immich-gallery
  template:
    metadata:
      labels:
        name: immich-gallery
    spec:
      securityContext:
        fsGroup: 1200
      containers:
        - name: immich-gallery-server
          image: "ghcr.io/immich-app/immich-server:v1.125.7"

          env:
            - name: REDIS_HOSTNAME
              value: immich-gallery-redis-master
            - name: DB_HOSTNAME
              value: immich-gallery-postgres-rw
            - name: DB_USERNAME
              value: immich-gallery
            - name: DB_DATABASE_NAME
              value: immich-gallery
            - name: IMMICH_PORT
              value: "2283"

          envFrom:
            - secretRef:
                name: immich-gallery-secret

          ports:
            - name: http
              containerPort: 2283
              protocol: TCP
          
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1

          volumeMounts:
            - name: galleries
              mountPath: /mnt/galleries
            - name: library
              mountPath: /usr/src/app/upload

      volumes:
        - name: galleries
          nfs:
            server: vega.<path:core:paths#domain_lan>
            path: <path:core:paths#nas_storage>/immich/galleries
            readOnly: true
        - name: library
          persistentVolumeClaim:
            claimName: pvc-immich-gallery