---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-secret
  namespace: core
spec:
  encryptedData:
    cloudflare-token: AgBzFr6mUue+h14bGn9MW7n2b4Ozoe23pwd1R3y+dtdrF2ZpHqeOSZ7vbe1v4SOUoQPlGIT2eqWeo2Z/iw/wYEZWioZvd/q07rThrh0/CZMHHU5cvx1PXieOyn30FCZo5aKXAuA41rhs2N+RRQWcCwDWeSO5lE8ZHun+rDmFX8/etXNNakCGgVtYfLR16ZIccKcB+WbmInhKgyD+e47Hs4IbSJM/lWgK/NEML7ATKz5WTL3BeUIT65TPefdsNEeNrwkqI125wR9XQGjOfkgcJ8GzTRfzc2cR3XcO48r4G7OhAp2zfo9+gNQp+e7JU8iWzOlDoBJe+VoldrKdYSv5rIwGAjf/y7LV1HOuLXU6Ij9MFtJQlgzc2mSXhAT4yhoI9GgSDRD6Ib7i/uUIZZiXuMb6W8zE3yrx9Oz7NrhWXv+uUSvyeSlyiVCP6zOYUHvdDiJZ6Rmb81WcZ0/mzSNKhN4HLKAMTH4J8RFD+ZREsPOo5bUhnANL+98nj3loa2oN0FTVYteA7kt+tgfGc4ze9QxPqq2BgCAlwBPqRfkEmMBDQKI+5cpy5wCM4aMNOygRVz87igTUtcurIkynmWFJoZgwQQOYGlWhEJqvSiyt8YLqKTMwmiedQFN9dmtHL6XBs5sJFQPH7OrhYvAJvOuVjJxaqYjgIyDRG/+yLG5N50HYgZaO9gf2DzqKqTgWm7an0BgYH3Sgqedn0Hxt7FOGvmU0X63FsbzScSYUx7O5asZ8VlzTQS42QXYF
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-secret
      namespace: core
