---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: core
spec:
  encryptedData:
    domain_base: AgDCF2qbLqlqwfh21BcXXhkhNgiUCIpMsce+A/xXBCBmxbTN/PvDnw7tWkfiT0mz/6PErRmlLWeKAo73VkWQ63mVLjNl5A8HWP/K5xHH9jaoK5WzNluLaPyi/TVdyKHjTExDQ9IxOxyMHQV7qIwjtKRcyHb9HGRBpoCc6hoX4rWn6WJYb9RTG5aRrGYccuTiV57JbkL2UjqWyl3TK9rDi4yYDdiOTZehCnCqd1ApzlUmIF+ErlnVjFlyOpk+lw5335sfh9gO8btq0vaW92VVVl7kk1zMIcWmbx5TtLS3/RgPyCbemCK211aDKFVAHzu20Sne/D/Dz9FbS4wumXTt0JLQz0Mk3iT+4kDcgZgRj3WKKH/3U9UL0O9fmRDqV6+JdbYWdWGrfXeHhRh1mi1x0oj/07An7Te9UwOukiEjuq4/5H1Myss5c1Naqx/xc/eKvzkTuLy0s5I45ZCQZHH4LepNG08dZVogGS2TktipKeDHm5Qi4izwbsaJLUQDyDf715E7zFBdW3pZgQylijUTW0xpLPY+c2lld78dIDOJ19VsKQtMGwuyYoToDW55cq1l0oHcCuV07nhynjZP4kMrcC7FTyPNnBISZnQmjEBcj8+j/mF/BA2hiS/qyW0UCRCZIR6gZxSVDcC8AuGA8lV94x3jLCoutMi5HNTeC0EFdP9/lqY+P+prJM6SFhHKlPDCEJi2hP7OhSVZjMIoOZQ=
    email: AgBpibRXnAp76v5GqRS9Kic+WQaEbOLvnmnjJd2G0/AnNcDm2i77pXkB09Xl2TFcAuE92GcZSVh1jgHEAyKmEhcQi5o+lHfTqFW+lXvYVGKwhvu3kljw6uGOG+h5jrk7bda1fKv8/m2uf026rgTuoPsD6Glz64HDUrtBGe9uGbLH6TksPluadt/X5T/MILxB1qwmossvboeqgRFoqHmla8CZHnPkCKsiQiNJ8hmAKzQV+i70T8fG2ZAb7FVccUKYu5228OuIfd0/qI1PhEPp2q9MCsnUihxy7AGVH6MXkdOXnc6ImPvE45MznYsDgM/A9MsqUDa1E1fjdK0s9WObx8ihFe+tWRCeHhdBdTU4ATltuh3thb0jHjggk7JUtCS4sSzVBXOZP2pNzIvnIBFl3akMpjM/z26piGx7PEhDo1Cc8faTMTdLqnrC/aGGfhJmUnqdyDg4C4RJghSU4SLKCv0JM51+nMpGYsACxDVTt2jgbdZM52bhvWYrWLrFl7IkpEUwrgHc87m00RXjGDYLGySh/xDkTs85bShgLSTTLrizFO57wA7or/CYRR0gDvkLa84ND0xZsmRtfkbALCx/8oUckb0ygG9wo1GsMA4y4TXZ5kWxibLbQL/63MM6l6fjm0yYHtLh9UFZcP50XvhxQH7giYz4b1u0JtkbHgePSnt/kkfVbUbnjjZPsCz1+o2Ul8Z+EP3WDL4EjuUto8Dao+2lX3pubnNW5HE=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: core
