---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare
  namespace: core
spec:
  encryptedData:
    domain_base: AgAXxWFPxNLOFKRUg9rBJa3DGS0BG3KO34nHe+T1Vkp6qJubR1rlmYMP05i49nCH5g64naf0lRB/wINuXpEdvWi5YNG7wjUZ76c5mrxOdffQ/ShtBIY+kk2iZy+8H6k2IEKvw6qY6vyLu6oLb0Y5tXK2q0ABzyoQGe47txDSY36167R+G69zqSfeC8VNE7o7vo8PYFnIabH4PpiqJHlge06nfmxvRzonAfEw0JHi08yg6t5iW3XHJT7J4qqK0ykTH205o6S9QoPtXFnjhmdH0f44mRW7/F5aNp4R83Ibyq7EDe15ND072nnh+3a75BvipXUsJRxIbsoe1CXDVYLAOPaY0TD6LThgix2SN5CB4OTek5QMS8fTIG54diCz2A5RHjDgQNGXIMkoRfR+IPjy4GQR9zv3BOU5fOhnFy3Rsx7eWdHgA83T2MHnsOMHtVskc+ytstal2jdvQuDwT9d6dbwqK6kKUGJ8GCEu6TJ1tqEN/9D8YJi51OtGkxgknED34Bz08b3Hm8rM3VHQZ51zs3nGLKf2/vQkcO7mQjkP6a4TH3swW04mT7a8Au1nOidxTSuvmADbElurnQphTqA3d7Z9hn2kxXDZ5JpSb8+0fhYZRKCKUyDd/9yoNviaXedLi38lOssZhmyH9PblzdidO32HQaUH1P1GfSStTu5EvznUoVHIr8+edeYXHtcKbbUHCsUJ3+QXKD8gTfqm9ug=
    email: AgAjsS2u7FxGvwwHdcd7VGeSVJML2TxQp+v9GgrjPHzN/504B4WB/eIVGp8v3U1cZUqPYmgMqB9xk5m5h2XrpzmGTPwi8Nd7VxPvDBalz5M1gyVb2dHoZgB4OqT11Wf6bPGalnJ6sIHsP9UTY7XAfubr4mRJIucRSdo2daUJcCh0LxwmGp+uuUWQovFdw48uQW6Z8zw8Q5VTCgGJiU8Yt4nb7HpuUzO65IDgKYY6BHz+0/dM/w7AnNo8ce1Alk2IyHqyfa/ph9oouAUQuhTNZ++ws1Pk/5TISQ/1+wNNIszXK43A8eFuYMvB+hSMzQmXoqzqxQxpoDqJy+2/J5D32GvDb2H4rQcLF4n84UZGpet28HARSe47peLQutS196xIXxHQz8s0nI+imYx0zOJfL2ueua3rnvjlU1znV3EYPkslKC48l8RksXeulwNELHmW4ZTS8YiWuzixPfsaGxU/yDeRiPnxyCBwmRdLkRGyxKTiSJbEJ0/w4rCa6Nik5dgod6LAhtTcL5UiAHL+lt+cscoJVfd0Rfi3QJkCGpPzG6xGOtvTEtXJu3CHDIvbOs1Fw0EmtRy8xFZ/B4D6PW6VNPe6g6GpLHBK6HUBxlsB4ojvTnmfQrrG5+L6Tll4Mfo5pulVdecN4S5uwyKRbyqelgwt91mwgodbKbjavDw74HfhMl03JmTj7nK0jIqmdvayTqYP8Qm3rvwhLzMiyw+BNiLnQ1xm5cZZjXk=
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare
      namespace: core
