---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ingress
  namespace: core
spec:
  encryptedData:
    domain: AgBDbjYEs226P+fGln/3kgANiiHCJqJyk8QGyim2CtkRLXQVI4HawKUHnJxwWJj2k0+m7pLVzBR8Bv27/uh49zhYi9IssTKCpf7EAIDWRdIG0fisQKKKZXfdePm9sU9UiACrfCSE3GSK/vMqALkEB9/8VJCWj6etlfBAq5zP/RV2id0AuIrybMZfT8KRYLofZTcfb4UM8df22VlSpEk038VWuBzMW07qPyUcUN1Xvn6E9k01EkkJUG+xtw06EvNvv8AqUtdGKIQDyJA9a48D4xv731NbqAgKzbg/6YIviYPO+M3xxL3FVKnE+eNLLUZKHiAU3jAicZUbDS5IvoH+NI9/En+9Lyztab++db9zNWhoBbhB1rxV8o7dUtGSEkFbfVvZvOmq9c2afu7B9ROCrP4s920lbt7nx3JKXLp6uA4J7/KtxexmZlFKpBHQgjcz9qm5bPYNF/1mBlPsLLIRVPCVsfaRNhjuqcdg98tPhTkUh5Fo/UQ+N5LvQarK9vVKN2pMvbxY7JGvsxiBUql7qS6F8/KWJ0DVU3xAqPIgCpI/txWTXeXTQsSR/pS+eV+lchFavGaY8g50vEnsAywht48bVR+meloVh296MoIwy8i/r1+cXb/cwK2sW22pXSYIBHPH/vpJwjK/+FkbrY7kPEI1EizIhA1wFq/NkA7pO1jWEDbbh+Wvwr/RBpZLrPorvXsSkf04gDwjrdB/KT2M8uu0
  template:
    metadata:
      creationTimestamp: null
      name: ingress
      namespace: core
