---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: media
spec:
  encryptedData:
    ACCESS_KEY_ID: AgBwar8RH427S+GSZ7mYDvO0jx0Ga/r198F0V27RJ8LToNDmqXFhiAWKEo+RArDYOs2b0xnC3FJwVYzlnw8r/Mk+84f6HpkM+wq1DerbXEZNnjPf/V6hzpo8cdojkZeHZEhno5JPp6kwk4lcoFPoFoVIcwlThb1QVZ4A0RKkcFDh8N1jqFWNGTnp9pLSsNz6/kqAOfoTz3Oy4lG9HMoz4PnP10EU2qa45nADkmi8RuIRCo8STlN/zRYAg01KVpvyzxM+UnyYhYkkmWV8MXYZPe/DPddahd5WHU60MWuBEfxw5kQbXVC68nQnu9kzRJaS8Lw3Aq4oC25Jqrh5TYo5GXoe+/rUVy2p4nMjGPnLDx8dWBbtQugSnAapvWifRsgN2rV12+ejHjDOT/viKlrrnqw5PQGbBBS7RRHXyaNFs7kxstwCxHkSAE1f1La38GV1swhn3QYq1oC8w9IjyKoAR49Wq2PaMMsP9SUFEgBouXG1Y6QHQkmNRM9ecyXkz+2fxbocoPKwe7MMujcXFOn/rlibBVbkSCna+CpKoACgT9t5Cjp+qxgpJs4DdHsG7+7QUkQjIQN/YuHCtMW/yEUwDHtBlZzhsrSexzEBlhReEaHABPNoBbm7RBrujpKL3PSqZkvp3RG3kim1qRTf1G1aKu3VBD2d3ffLOVDkSIupnVvjjIN8vFI4IDKW55dvgNabKKrEwg54dssVqGfgMDZEiLaPn6ct5w==
    ACCESS_SECRET_KEY: AgBqoZH+ycMy+aqGUwI15Y3svd9jj7fIXjEA6yW1RdfXoEt+DCm11D029Tv4vT0m78l+0+la5vqkYqHRDn3pmAW/hhAPf6ZJEeVT0IQkOBnEkyeaQ9Av1Rpu6ihGNTTnJK0qVGmZZP6Ks1lQtcyT7JBTxbf/6TxN3uHMOPyE8aHEQDRMrEYUpkXQMmM73j4c3W9GyZYKNkbwmtxaSt/lfjuhpUg0RfWiKOZxcR9NH5XvWDW4wBKg4Swl9ni0SN4oMUppsCA8h0pUI400dXHnNzWAWQn7YZdBVjEmmq1ws4hi/CUtXgFRBg6jlWx7h0I4M5adO3wNtTEqENUtbIBli+on2I/1LJ6eXQB4T/OVJbLB54KZXpGzvRpSirh0U4QTAsoRP9J9aKlHgYnpzh3PIuGRXiSxFihJ+uR8+q07F5JWR/mBOInhTExIjS6hnDlEljEbI3q5DYp4W+R0p3EWjZ2pdM7KnnoalS8d2db+S9KCz6aeb4kky9brYaYi/oJ2IDIGEMOMY0ww5opXMVTcCK8u0bJ1iVPDddryRsapZ/g+l7yhCWr4Ys8EpPsjB/ez4GqasN8jrRIphp1MHi7TA6QDWNXKg/UpeOnE/bcrPp7F0ExMPquP3wg5O6fSFM1DAgfWMcfUsuehXbuIhXsgDno+NbKuvdRXTXw0d9aimZIYbce8IuhWRK1cJMSWoKtYiygbY3v1OVd6Zpd1ltY5d9OqunMCVxsgal5L6YdBsS9FOSQGqIMEDkp2
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: media
