---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: media
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAVzVsuKR1Lm9ude2r+Axljw9UAXW52OBIaAOLDtUpDRhCD63E2T0HrE2fah3UnuEXdkjvtVyulhNHf6K3+e6a5FFEHX3N4oRM7jH52ZP0drVSPGORMmnwRIeg6bpq6b/TG44d+ruwNMOuqG7A035LA/hvxR+rPhW3sVAr5GliCOWkniBXL16mrM6qft7vTmdhciS0biGnJWV7HVkoujnht4bc0RoVwE3zW0qhrqeN6Zqm7hKLOYLKasYJC4lgRNlSkkpyff1VPCw51moAeQ0rmCyN6ut9x2Xw/MSI7ubvLyYW+uiGQFZZJBSA7KFSXChl2QNLSTpJ6bRiKrB9ooHrdWASZVSbtxIenTrrG63pg9U92PPA86VYzxf7rEQxtsVrjRvQZdVxg+l3opLpTMJP/3MGE4PBGvxyULASPr5XCDe7pbKHynDALcjUq5DKF2EyHX0vMJVWDF1QI+QbeNqO5tA5vXlnH+sWiTFKSN73QrDO5jMfq+y9XT6zuD0CXQ3dTdz4dzzPyiHM7fPpre0OZ1KfhAcBOjlq71pvpFTOJ5/XmEzvQpfAbXzILgNiuHdWwR9mmk4hXm/n0SOuHfLdxSR+NRczXi9pf4Qp50WkA7+VkFUxuTgH0bflxvccmRhA05r6ndDpgi/S9WuhvR4yKWgdgjSRxlrAX5Gewqc/DoPuFCM/ZXryJ5jQ7CCBpvJ0m6USjgZOIGKOnvqdWDeHJDXAaLQ==
    ACCESS_SECRET_KEY: AgC0XqqLFVbpJ2Ys3hX9uJIVl3SwYKlJZbbkC+F4fOd1w0EfjvNXmi8DfsZatt237XBEyGAjU+ZnE36VHULo1FfuIZ1im90lq+FbaAur5M6bDPUmEPZPbvrB5hkQ0VtcuW4FhAhrR0WH3KnB8Inh03A+FEmUYqb9s2Ol7Z+Qnwx1BYu+GdWSl8SW6yijQusydLhfwaWe15icgH22Fqp3Cnzf7rb8O8CUs0en5WHKW1EutoLcL2OWd4FneaZ5KhKglh7Xbx8nX1aARmj/ljHbJOO43du5G0fzRoQdsgUgFdo0kdt3/DyEULehTZdHONIJiK0ObL/6obYCcFm+OsaxcYm6BPMe2QHszrq4mhw5a2tfPhry16aooG+81VmABpYJiWCsKcljbYOGO8WGbfUSfWZyvBgpFMGxW+iREkhgXgIafdYR1kxExMwKBZSP5RoL+RaLdlJqhsOcyciv/7vPp3ZYgsHMfyTVf1wi81pNoRYzdtKi2XZnHrcbs2aSEwwyhSX429rOptyC8n9dMOupqspuvRcpXnV+zt32VzV1PWR5PJB6nVoHyJY3szH8WNqjG1OLVW7TSkpfcjkhxnUUyX1OlejOvyj4e7XBNyNTMD8b5yG7sJb8O+F9a4FL7Ftzj3EH6CQS9rg7Gf4jTCuBzZv8CPo3k8uIPeNc3yQV+vhS4E8eq59LIEQJK+YKOHlG2B4ZntlsZ2erhbAAos978mbE++0+0UbCO6/tpvvnjsHl3HzB60FoEPvH
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: media
