---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-collection
spec:
  revisionHistoryLimit: 3
  replicas: 2
  selector:
    matchLabels:
      name: immich-collection
  template:
    metadata:
      labels:
        name: immich-collection
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: immich-collection-server
          image: immich-server

          env:
            - name: REDIS_HOSTNAME
              value: immich-collection-redis-master
            - name: DB_HOSTNAME
              value: immich-collection-postgres-rw
            - name: DB_USERNAME
              value: immich-collection
            - name: DB_DATABASE_NAME
              value: immich-collection
            - name: IMMICH_PORT
              value: "2283"

          envFrom:
            - secretRef:
                name: immich-collection-secret

          ports:
            - name: http
              containerPort: 2283
              protocol: TCP
          
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1
          startupProbe:
            failureThreshold: 30
            httpGet:
              path: /api/server/ping
              port: http
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 1

          volumeMounts:
            - name: collections
              mountPath: /mnt/collections
            - name: library
              mountPath: /usr/src/app/upload

      volumes:
        - name: collections
          nfs:
            server: vega.<path:core:paths#domain_lan>
            path: <path:core:paths#nas_storage>/immich/collections
            readOnly: true
        - name: library
          nfs:
            server: vega.<path:core:paths#domain_lan>
            path: <path:core:paths#nas_volumes>/immich-collection