---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-immich-collection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-csi