---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: media
spec:
  encryptedData:
    ACCESS_KEY_ID: AgDEqQzwVclqlL/bv3LzuTUj1wXX5JXSao2Dpp/NFfRd3i7SsW8lBHNIqeqEiDWWxeHrn9nkIHFjJAx3sonf8MwB380z5W1DclwvCKNZqP3JiU8QMP1vtEAi7Uekm/sX3JkStDe1T6mrhZp0bbu+f6CQmGghadACgXPGdgQ2PyikK2BB/K6YVkZorZo2x2VOgrnwJAqpoePMACItW1yzSt7skBaoz62QJP5N0xoJoxi7tp0XDAxS+9yvItJtvVfJ8DoHx9OegtwpdFV+IyluRmXwTCnvfrHZShi8T9jI8yu37pexV6xk0tGVp0sWyFthWcYvgDHCru2pyi6mOhWRT4PxH9KAf4sutkm76DKzNpG6joX5u1aNs8aRe2oiR+7c1NdeQwpbMzX8gg0LdbDLLurpNJFsMNt8/cRpQQrJ1o0i7tcWurStX+XvvOAbGppbpAONJYwZKy775quu6PE3nkv961aZflKj/Rglidi7NrGic8suBRXxAM94tcbDsjfjKcyQH/Q6aQkSv4jBDAuQGjkO+z//dEDZiKocTWMYKpFTKsVH5EhdMWaIpMKPMFHv+2XCRNTf+qfQhBVc+eHj9w3wt0buxCa+PWOyeTWy1pleEB+tdjf0O0k9kDndzdFEyD5Z2QE0Z6I3Q7QELAuivzMDUgnIiSAdwRH4Xj4dk6AZ11GyMfgCdPwGHF7W6R8EDZb+eMOyqpOYvCxUQ4WpPSwLKh/Piw==
    ACCESS_SECRET_KEY: AgDF7rYHdvEaqbmtHoPLvhFJw8ys8x/JnufAlCAOXCQ/CoGHR7BZu2fkn1AU0tyPjg5YY4M2gZmPfY6eAjjvLk3ZxnrXT8Uq6RqbG1QnYPv1iboY97taygMhiK7s5NnWXIQ9NbBz5qbL6Db/XtnuK0lq9tdp0vQAZzSYnNCDWJ2xsVFDwCGtwf9cvNzEbepZaES5ZMFyyWdK3bPuNYRkKHEb2ziXcGEPdl1okgOUzeHYs1vOMlbvBlcl3QRL9rrC+JE6UaQIcGwI9PmaW9OiTknBz3SjpeBghSvM1AY672e6vAcL7LDaNxcFNaTOihWkA1KzgDTpMrMCLeLH/ovl/GhHxXdW5S/eja9N81L6bkbWa/XWd0wQEO/9QBDefrX1spYbHB6iKG1NTKr1KbJCEycEKD1avLwxTiNYyjU+fbrJ1V2h/5cDtnznOXaPKBNZTgwQUFN8/YPaVHF8VbClIytkosX6TSQfTkRGlPofOMolAVeCOPKJGZsIImtrO6qpnK9qCRlZfsgEj09oYaL7U59UJSaINH2Es/LJpsQb3kF4QwZhZiy7itJ9mAOACrBJgXvTnoH4vQ0Y0g1ueLbfvcmT/DRuyta3cSGZ4IjCz0T0zzIgB+rj5yePQqe8T074a+44WXMdJbjvlveEzmy0Mhdeh57lT6e1vbUze6h5nzfJEJWTSY3zA8xTF2KglzWJZNpbtZm28fMdpkV9DlPsZ+Lnm+RBl2NSKeF7XzIMAt5pjaf9ytMgu7cI
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: media
