---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: operators
spec:
  encryptedData:
    clientId: AgBXP5jcLDRfy59eCcR0LEtKbeCt19Ze8XfzP/1zK6E+geeIm2yBZLDhud8IaspoaQGodulxp3TpS/fbDXC/43rxn5KcBEHb8IKJ6RYnWrdKhka3iJ6bZ7qBMP5ja3gjzQ3ZSR7bBRUpic+a7JUlb997peaxFWjdfaUBLMybYd3HDsk4KvMQY9V9DLhDXOHfAFjk/mrSphJbqzWA5hbGLP+yKZSKaqQPrXYqO5krH6T9ycjLFT4ta4pWGuIkkh2VbR0cXci48i5KGiiYpg9twSim4CvEWoqRGlJZKPYg8M1+d5CEqvxPpvahwDOag65/BPTVbbRYREuhGNCt2xboJNDrVpTESNAMnlEHoDeMdkqJ6PD0cwVpbtfX+5eXFDA9nWk8nJabvHj7pl9OYQZMuqoodKQ3N+aGGd4QGTXRQX3PPaRCrU1Ud+6bWfoUjJdMo2K27vF7TEbuD3c7WVbn8N42R/6+b3bsILrBEOffGXathLE5OFVQJINrcWxjU0TTXlBH7W9d1I6RgqNuxOY0uV4E/IkvRTZnEoGUC2N4uJfC+YMOzPapsLaedIFoextxqtoLbYhAXeKuzOEgGeoMwbBBgiSKlt1XgVOsE1PvHrcZCL/91dIywnNOtamBoMbkYTEDqOX1dJij9DkMwZVEQYhSFFDF/CZfkZ43yJS6EeT92LnzXUTPb9UkGSzmlpg4d6fHkKT1wYD3Y7yH5v1o2Fr8fg==
    clientSecret: AgB/XR39cTW7jFBfNRyUSaWaoiMUenxMaQEJcdIw5F5WBAAqGgGjTnu6bDYUwTxICA0Tnf80ataj0SJyOQN4coKMAzbkH5HNlB5JSR8E1o2YakVgZ8Mu4RvrvdwTcqEkEeETxNXYD5LWBR37QocmVQLGz2XbNR3Bpm6dybAW2UE/BFIPvds/EvLQO/V8Z/2eOO10uL/om7/0TgbjWsOp6qH94i7e2gJMXW7vKpIBRnT4qEOhYETVNeLaQFJSLaaCi9okPF0s3ixuvEmx2MwsnmUL6lwoZ2+gK6b3j5Q/pIoyujALEHgtCib/FG+6IJAcZe0xCTLT1l0PXy0PP/GA6WuolZACMyD0SApyuhDiZ8mgkgsJ6xou4z9f/lQJmH0JG02Vg/0eeuWn7qaTo8t7QkUYUJ0sRwA/Q2x4NbkHqQLTf8MKwJ4LFbFVuQSbj/ksBWxUl3RylYdiwf8nwSsDtY/w+1YvsgacMCv7DgW8JXkCW+c9bv7U+r+K9vlAV+5HyVjGW1KpRuuDCYeqWorQsxU+TvO0j1jt4ho+c/+A0KP63hcpRPHuJ+i0OeLF0B9sj2sI3NheMHsbWC3KYY4qc+YxghsHI8lHLcf84RCyYXf9hDdKkLbaytKH6m5k536CQzLVN899VOW/x2jDA7dWShdB8LOnW+n3RXDrvbqp8TSgZqrUSIYTuuHGKkw+wZuJ6EWhmvRLbvK9MMhGfGJXbtXSQ06pkZ0XsIEdN1I8Vk/mIaQ1Oxypvz/DYk/cJFklJCTwHHGX/ZntchcRevEZsOg=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: operators
