---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: operator-oauth
  namespace: operators
spec:
  encryptedData:
    client_id: AgACGvZGiZISf3ffpkxSpPYwpEfdtxAPieELP/315YzXlVGzdlcV9+Bun+jYfoK9Gq6hXKypBp8X0otNK0iADZOuHiA3b3S6y8/eQAYYU/7tAKYq8f6daVPKRvr/wRIJ/cwssWWrdq1xH1OBgWQkLuf1kRG3TJY82GC1UNybG7KZ1tGGc1KDpePDyaFwEdZU2eezf/ZZPX2sQB9uTOA/t+Jb2al3uzdLqs0AlkkkjZnj/9bErLW75WMYtygq7Jna6KjVA10noUU1tGm3gjJXOrgwOYNO5MM0WYPcOn+SAKgt9MdABKYDUbJPWnNVBsieoHxdw3syDbHfYuzjx4xxSW/bEkpiGaZGuV4pwKzkC080DnvcXjpgV9LLQT+cCtj5EATg5ZA1vDTgUA9mWCB/2MBwvRbiZcqCbbuF9I156cMyC/IKVqPh09tiOkyQ4QSLPw3JV6f/B1e8Bbs51hGKgraUogW/JHalDWvaESMlmGwhMRQS0ja3Z6Lg8bNkgnXHZ+kFxHpO8YkBw5kH7Z7xlDMTw30H42/Pm/u4ZQ0aK/FxZsFZ7cBOsgJb5IQGADGgU6nMicCyGNEx4KFN0FljWRkX+N4fHYAVR1vFoo90yQeIelwpGDlDTDeikja+pu3GafqZIGlVReDRgDWAzzdkfFy9hkIcZvvgCzwh+XOc0CTboIl5x4yqA3GQ4xWibG3z5SMg8UjZpOvobDJcHn7DkV2U0Q==
    client_secret: AgB96fzqOzZppvISuXBMK7cdo4B2sa8sZAReDUWvieZUf9hIFzmcxiI/FFyOntiF1IXyJkLI+E5kcEk6GHRnULfKE/QqZySJndl6Mdt465D7WJlWlZt44HbrzAmBcuSaep5HhMYqlgGChI9qFck8ItTuEf5XfQ6bL3XDFHk7Qaw26eSy6Cx4fCHVJaFdhwZ3YPVBIH4FRl23bvJAZy52ScV5dpmysAZAP3wQBSKI1TjHgE0/OQzCM4oj0pyLVA3b6zgAuHEFX76j/G9jYC80lNx9IayS+BLV0hABeIFf3uPCy/koOa9mU6Xl9TG9SoWZHtuFSz1fpSn16mQZ6wISkDYdxFTBnjMBvoEHMuLDtJoOPEZj8QtN5E0lHvftLtHSXAZ/DL+MMWR2IiBE+Og5LmSoWk44iV7TFseqRGFhldOXYfe1uQYzyFYbG/77y+vXcI0XpQTeRK1g9kOH/i4hfBp6DE9AUHpt2QV8/Q+j54n11KmbLfLc5dbAFxTtxNw8xdMs+9KVmEdLayEbRX31wI9R/vJiThuS+o5MQY7+mRa69eYmx/ylm5L9onUuiYClaqH6Qj0ZiP+CwdqprGjTIc17b5h5RxXjNMybjx4K6RcfRnOYF8BmQObud6a00UhTrabozI9dpHzHNlebZNkipB+1eQ4oIGjVvZvYI1VeufPcrynER3IyKUyftdpy7ImuwI05qnyvp07jP4cE5+beC7BTNFaFH21okfCE2C+lZaIgpbeRVdQI0bJQrXuKfJ/cR93VtFmRbMWxJynyFty6DI4=
  template:
    metadata:
      creationTimestamp: null
      name: operator-oauth
      namespace: operators
