apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/marshallbrain/homelab-gitops.git
        revision: develop
        directories:
          - path: dev/*
  template:
    metadata:
      name: "{{ .path.basename }}"
    spec:
      project: default
      source:
        repoURL: https://github.com/marshallbrain/homelab-gitops.git
        targetRevision: "app/{{ .path.basename }}"
        path: "{{ .path.path }}"
        plugin:
          name: lovely-vault-plugin
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 1m
            factor: 2
            maxDuration: 3m
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply=true
      ignoreDifferences:
        - group: ""
          kind: Service
          jqPathExpressions:
            - .status.loadBalancer.ingress[].ipMode