apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment/deployment.yaml
  - deployment/ingress.yaml
  - deployment/service.yaml

  - postgres/postgres.yaml
  - postgres/backup.yaml

  - secrets.yaml

images:
- name: immich-server
  newName: ghcr.io/immich-app/immich-server
  newTag: v1.129.0