apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
spec:
  instances: 1
  
  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-secret

  storage:
    size: 1Gi